apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
  name: vault-test-pod
  namespace: default
spec:
  automountServiceAccountToken: true
  serviceAccount: vault
  serviceAccountName: vault
  containers:
  - name: vault-test
    image: praqma/network-multitool
    env:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: VAULT_K8S_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: VAULT_K8S_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: VAULT_ADDR
      value: "https://vault-0.vault-internal:8200"
    - name: VAULT_API_ADDR
      value: https://vault-0.vault-internal:8200
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: VAULT_CLUSTER_ADDR
      value: https://vault-0.vault-internal:8201
    - name: VAULT_RAFT_NODE_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: VAULT_CACERT
      value: /vault/userconfig/vault-server-tls/vault.ca
    - name: VAULT_CLIENT_CERT
      value: /vault/userconfig/vault-server-tls/vault.crt
    - name: VAULT_CLIENT_KEY
      value: /vault/userconfig/vault-server-tls/vault.key
    - name: VAULT_LOG_LEVEL
      value: debug
    volumeMounts:
    - mountPath: /vault/config
      name: config
    - mountPath: /vault/userconfig/vault-server-tls
      name: vault-server-tls
      readOnly: true

  volumes:
  - configMap:
      defaultMode: 420
      name: vault-config
    name: config
  - name: vault-server-tls
    secret:
      defaultMode: 420
      secretName: vault-server-tls