apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
  name: vault-test-pod
  namespace: default
spec:
  automountServiceAccountToken: true
  serviceAccount: vault
  serviceAccountName: vault
  containers:
  - name: vault-test
    image: praqma/network-multitool
    env:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: VAULT_K8S_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: VAULT_K8S_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: VAULT_ADDR
      value: "https://vault-0.vault-internal:8200"
    - name: VAULT_API_ADDR
      value: https://vault-0.vault-internal:8200
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    volumeMounts:
    - mountPath: /vault/config
      name: config
    - mountPath: /vault/userconfig/kms-creds
      name: kms-creds
      readOnly: true

  volumes:
  - configMap:
      defaultMode: 420
      name: vault-config
    name: config
  - name: kms-creds
    secret:
      defaultMode: 420
      secretName: kms-creds